# Generated by Django 2.1 on 2018-12-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181209_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replays',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
