# Generated by Django 2.1 on 2019-02-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('base64_file', models.TextField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
            ],
        ),
    ]
