# Generated by Django 2.1 on 2019-02-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='replays',
            name='missversion',
            field=models.BooleanField(default=False),
        ),
    ]
