# Generated by Django 2.1 on 2019-02-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feedback_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='data_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='bot_player',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='data_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
